apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: kawachoupipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kawachoupipelinesjavascriptdocker 
    spec:
      containers:
        - name: kawachoupipelinesjavascriptdocker 
          image: pasturecr.azurecr.io/kawachoupipelinesjavascriptdocker
          ports:
          - containerPort: 8080